a=3
try:
    print(a/3)
except:
    print("error occured")
finally:
    print("executed")